config/routes.rb
Gordon::Application.routes.draw do

  get "users/new"
  root  'static_pages#home'
  get   '/help',            to: 'static_pages#help'
  get   '/about',           to: 'static_pages#about'
  get   '/signup',          to: 'users#new'

  resources :recipes

  resources :recipe_ingredients

  resources :recipe_steps

  resources :ratings

  resources :steps

  resources :quantities

  resources :ingredients

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_and_belongs_to_many   :recipes
end

app/models/quantity.rb
class Quantity < ActiveRecord::Base
end

app/models/rating.rb
class Rating < ActiveRecord::Base
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_and_belongs_to_many   :steps
  has_many                  :recipe_ingredients
  has_one                   :rating
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/step.rb
class Step < ActiveRecord::Base
  has_and_belongs_to_many   :recipes
end

app/models/user.rb
class User < ActiveRecord::Base

  before_save { self.email = email.downcase }

  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  # presence validation for password and its confirmation are automatically added
  has_secure_password
  validates :password, length: { minimum: 6 }
end

app/controllers/quantities_controller.rb
class QuantitiesController < ApplicationController
  before_action :set_quantity, only: [:show, :edit, :update, :destroy]

  # GET /quantities
  def index
    @quantities = Quantity.all
  end

  # GET /quantities/1
  def show
  end

  # GET /quantities/new
  def new
    @quantity = Quantity.new
  end

  # GET /quantities/1/edit
  def edit
  end

  # POST /quantities
  def create
    @quantity = Quantity.new(quantity_params)

    if @quantity.save
      redirect_to @quantity, notice: 'Quantity was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /quantities/1
  def update
    if @quantity.update(quantity_params)
      redirect_to @quantity, notice: 'Quantity was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /quantities/1
  def destroy
    @quantity.destroy
    redirect_to quantities_url, notice: 'Quantity was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quantity
      @quantity = Quantity.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def quantity_params
      params.require(:quantity).permit(:amount)
    end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: [:show, :edit, :update, :destroy]

  # GET /ratings
  def index
    @ratings = Rating.all
  end

  # GET /ratings/1
  def show
  end

  # GET /ratings/new
  def new
    @rating = Rating.new
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings
  def create
    @rating = Rating.new(rating_params)

    if @rating.save
      redirect_to @rating, notice: 'Rating was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /ratings/1
  def update
    if @rating.update(rating_params)
      redirect_to @rating, notice: 'Rating was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /ratings/1
  def destroy
    @rating.destroy
    redirect_to ratings_url, notice: 'Rating was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def rating_params
      params.require(:rating).permit(:name)
    end
end

app/controllers/recipe_ingredients_controller.rb
class RecipeIngredientsController < ApplicationController
  before_action :set_recipe_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /recipe_ingredients
  def index
    @recipe_ingredients = RecipeIngredient.all
  end

  # GET /recipe_ingredients/1
  def show
  end

  # GET /recipe_ingredients/new
  def new
    @recipe_ingredient = RecipeIngredient.new
  end

  # GET /recipe_ingredients/1/edit
  def edit
  end

  # POST /recipe_ingredients
  def create
    @recipe_ingredient = RecipeIngredient.new(recipe_ingredient_params)

    if @recipe_ingredient.save
      redirect_to @recipe_ingredient, notice: 'Recipe ingredient was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /recipe_ingredients/1
  def update
    if @recipe_ingredient.update(recipe_ingredient_params)
      redirect_to @recipe_ingredient, notice: 'Recipe ingredient was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /recipe_ingredients/1
  def destroy
    @recipe_ingredient.destroy
    redirect_to recipe_ingredients_url, notice: 'Recipe ingredient was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe_ingredient
      @recipe_ingredient = RecipeIngredient.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def recipe_ingredient_params
      params.require(:recipe_ingredient).permit(:recipe_id, :ingredient_id, :amount)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      redirect_to @recipe, notice: 'Recipe was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /recipes/1
  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe, notice: 'Recipe was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /recipes/1
  def destroy
    @recipe.destroy
    redirect_to recipes_url, notice: 'Recipe was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def recipe_params
      params.require(:recipe).permit(:rating_id)
    end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  before_action :set_step, only: [:show, :edit, :update, :destroy]

  # GET /steps
  def index
    @steps = Step.all
  end

  # GET /steps/1
  def show
  end

  # GET /steps/new
  def new
    @step = Step.new
  end

  # GET /steps/1/edit
  def edit
  end

  # POST /steps
  def create
    @step = Step.new(step_params)

    if @step.save
      redirect_to @step, notice: 'Step was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /steps/1
  def update
    if @step.update(step_params)
      redirect_to @step, notice: 'Step was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /steps/1
  def destroy
    @step.destroy
    redirect_to steps_url, notice: 'Step was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_step
      @step = Step.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def step_params
      params.require(:step).permit(:content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/quantities_helper.rb
module QuantitiesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/recipe_ingredients_helper.rb
module RecipeIngredientsHelper
end

app/helpers/recipe_steps_helper.rb
module RecipeStepsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/recipe_ingredients/_form.html.erb
<%= form_for(@recipe_ingredient) do |f| %>
  <% if @recipe_ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe_ingredient.errors.count, "error") %> prohibited this recipe_ingredient from being saved:</h2>

      <ul>
      <% @recipe_ingredient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :recipe %><br>
    <%= f.text_field :recipe %>
  </div>
  <div class="field">
    <%= f.label :ingredient %><br>
    <%= f.text_field :ingredient %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipe_ingredients/edit.html.erb
<h1>Editing recipe_ingredient</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe_ingredient %> |
<%= link_to 'Back', recipe_ingredients_path %>

app/views/recipe_ingredients/index.html.erb
<h1>Listing recipe_ingredients</h1>

<table>
  <thead>
    <tr>
      <th>Recipe</th>
      <th>Ingredient</th>
      <th>Amount</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @recipe_ingredients.each do |recipe_ingredient| %>
      <tr>
        <td><%= recipe_ingredient.recipe %></td>
        <td><%= recipe_ingredient.ingredient %></td>
        <td><%= recipe_ingredient.amount %></td>
        <td><%= link_to 'Show', recipe_ingredient %></td>
        <td><%= link_to 'Edit', edit_recipe_ingredient_path(recipe_ingredient) %></td>
        <td><%= link_to 'Destroy', recipe_ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe ingredient', new_recipe_ingredient_path %>

app/views/recipe_ingredients/new.html.erb
<h1>New recipe_ingredient</h1>

<%= render 'form' %>

<%= link_to 'Back', recipe_ingredients_path %>

app/views/recipe_ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Recipe:</strong>
  <%= @recipe_ingredient.recipe %>
</p>

<p>
  <strong>Ingredient:</strong>
  <%= @recipe_ingredient.ingredient %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @recipe_ingredient.amount %>
</p>

<%= link_to 'Edit', edit_recipe_ingredient_path(@recipe_ingredient) %> |
<%= link_to 'Back', recipe_ingredients_path %>