config/routes.rb
Gordon::Application.routes.draw do

  get "users/new"
  root  'static_pages#home'
  get   '/help',            to: 'static_pages#help'
  get   '/about',           to: 'static_pages#about'
  get   '/signup',          to: 'users#new'

  resources :recipes

  resources :recipe_ingredients

  resources :recipe_steps

  resources :ratings

  resources :steps

  resources :quantities

  resources :ingredients

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_and_belongs_to_many   :recipes
end

app/models/quantity.rb
class Quantity < ActiveRecord::Base
end

app/models/rating.rb
class Rating < ActiveRecord::Base
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_and_belongs_to_many   :steps
  has_many                  :recipe_ingredients
  has_one                   :rating
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/step.rb
class Step < ActiveRecord::Base
  has_and_belongs_to_many   :recipes
end

app/models/user.rb
class User < ActiveRecord::Base

  before_save { self.email = email.downcase }

  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  # presence validation for password and its confirmation are automatically added
  has_secure_password
  validates :password, length: { minimum: 6 }
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: [:show, :edit, :update, :destroy]

  # GET /ratings
  def index
    @ratings = Rating.all
  end

  # GET /ratings/1
  def show
  end

  # GET /ratings/new
  def new
    @rating = Rating.new
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings
  def create
    @rating = Rating.new(rating_params)

    if @rating.save
      redirect_to @rating, notice: 'Rating was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /ratings/1
  def update
    if @rating.update(rating_params)
      redirect_to @rating, notice: 'Rating was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /ratings/1
  def destroy
    @rating.destroy
    redirect_to ratings_url, notice: 'Rating was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def rating_params
      params.require(:rating).permit(:name)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      redirect_to @recipe, notice: 'Recipe was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /recipes/1
  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe, notice: 'Recipe was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /recipes/1
  def destroy
    @recipe.destroy
    redirect_to recipes_url, notice: 'Recipe was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def recipe_params
      params.require(:recipe).permit(:rating_id)
    end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  before_action :set_step, only: [:show, :edit, :update, :destroy]

  # GET /steps
  def index
    @steps = Step.all
  end

  # GET /steps/1
  def show
  end

  # GET /steps/new
  def new
    @step = Step.new
  end

  # GET /steps/1/edit
  def edit
  end

  # POST /steps
  def create
    @step = Step.new(step_params)

    if @step.save
      redirect_to @step, notice: 'Step was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /steps/1
  def update
    if @step.update(step_params)
      redirect_to @step, notice: 'Step was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /steps/1
  def destroy
    @step.destroy
    redirect_to steps_url, notice: 'Step was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_step
      @step = Step.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def step_params
      params.require(:step).permit(:content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/quantities_helper.rb
module QuantitiesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/recipe_steps_helper.rb
module RecipeStepsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://wouldgordonapprove.herokuapp.com/">Would Gordon Approve</a>
    by Manoj Ganesan
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
        <div class="container">
            <%= link_to "gordon", '#', id: "logo" %>
            <nav>
                <ul class="nav pull-right">
                    <li><%= link_to "Home",    root_path %></li>
                    <li><%= link_to "Help",    help_path %></li>
                    <li><%= link_to "Sign in", '#' %></li>
                </ul>
            </nav>
        </div>
    </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Would Gordon Approve? | <%= yield(:title) %></title>
        <%= stylesheet_link_tag    "application", :media => "all" %>
        <%= javascript_include_tag "application" %>
        <%= csrf_meta_tags %>
        <%= render 'layouts/shim' %>
    </head>
    <body>
        <%= render 'layouts/header' %>
        <div class="container">
            <%= yield %>
            <%= render 'layouts/footer' %>
        </div>
    </body>
</html>